import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const languages = {
  en: {
    name: 'English',
    code: 'en',
    common: {
      home: 'Home',
      products: 'Products',
      recommendations: 'Recommendations',
      chatbot: 'Chatbot',
      profile: 'Profile',
      about: 'About',
      menu: 'Menu',
      logout: 'Logout',
      login: 'Login',
      english: 'English',
      thankYouForOrder: 'Thank you for your order!',
      orderPlacedSuccessfully: 'Your order has been placed successfully.',
      continueShopping: 'Continue Shopping',
      cart: 'Your Shopping Cart',
      yourCartIsEmpty: 'Your cart is empty.',
      orderSummary: 'Order Summary',
      subtotal: 'Subtotal',
      shipping: 'Shipping',
      taxEst: 'Tax (Est.)',
      proceedToCheckout: 'Proceed to Checkout',
      noProductsFound: 'No products found matching your criteria.',
      editProfileComingSoon: 'Edit Profile (Coming Soon)',
      productsTitle: 'Products',
      fertilizersNutrition: 'Fertilizers & Nutrition',
      pesticides: 'Pesticides',
      farmingTools: 'Farming Tools',
      premiumSeeds: 'Premium Seeds',
      servicesTitle: 'Services',
      palmpilotConsultation: 'PalmPilot Consultation',
      aiRecommendations: 'AI Recommendations',
      farmingGuides: 'Farming Guides',
      technicalSupport: 'Technical Support',
      contactTitle: 'Contact',
      allRightsReserved: 'All rights reserved.',
      backToProducts: 'Back to Products',
      register: 'Register',
    },
    home: {
      welcomeTitle: 'Welcome to PetanNaik!',
      heroSubtitle: 'Trusted E-commerce Platform for Palm Oil Farmers',
      startShopping: 'Start Shopping',
      learnMore: 'Learn More',
      aiRecommendationsTitle: 'AI Recommendations For You',
      aiRecommendationsSubtitle: 'Based on the analysis of your plantation needs, we recommend these best products',
      recommended: 'Recommended',
      refreshRecommendations: 'Refresh Recommendations',
      popularProductsTitle: 'Popular Products',
      whyChoosePetanNaik: 'Why Choose PetanNaik?',
      aiRecommendation: 'AI Recommendation',
      aiRecommendationBody: "Get personalized product suggestions based on your farm's data and local conditions.",
      qualityProducts: 'Quality Products',
      qualityProductsBody: 'We provide only certified and high-quality agricultural products to ensure your success.',
      palmpilotAssistant: 'PalmPilot Assistant',
      palmpilotAssistantBody: 'Our AI chatbot is ready 24/7 to answer your farming questions and provide expert guidance.',
    },
    chatbot: {
      title: 'PalmPilot Chatbot',
      placeholder: 'Type your message...',
      send: 'Send',
      clear: 'Clear Chat',
      thinking: 'Thinking',
      error: 'Sorry, I didn\'t understand that.',
      connectionError: 'Sorry, there was an error connecting to the chatbot API.',
      modelInfo: 'This chatbot is powered by Llama 2-7B model',
      consultantTitle: 'PalmPilot Assistant',
      consultantSubtitle: 'Your AI Farming Consultant',
    },
    recommendations: {
      personalizedRecommendations: 'Get Personalized Recommendations!',
      loginToReceiveSuggestions: "Log in to receive suggestions tailored to your farm's needs and purchase history.",
      loginOrSignUp: 'Login / Sign Up',
      youMightAlsoLike: 'You Might Also Like',
      generalFarmingInsights: 'General Farming Insights',
      exploreGuides: 'Explore our guides for best practices in palm oil cultivation, from fertilization to harvesting.',
      boostYieldWithNPKGold: 'Boost Yield with NPK Gold',
      combatLeafSpotEffectively: 'Combat Leaf Spot Effectively',
      optimalHarvestingGuide: 'Optimal Harvesting Guide',
      learnMore: 'Learn More',
      needSpecificAdvice: 'Need more specific advice?',
      askPalmpilot: 'Ask PalmPilot',
    },
    products: {
      pageTitle: 'Our Products',
      searchPlaceholder: 'Search for products...',
      priceRange: 'Price Range',
      allPrices: 'All Prices',
      under: 'Under',
      above: 'Above',
      category: 'Category',
      allCategories: 'All Categories',
      applyFilters: 'Apply Filters',
      addToCart: 'Add to Cart',
    },
    profile: {
      pageTitle: 'User Profile',
      fullName: 'Full Name',
      emailAddress: 'Email Address',
    },
    productDetail: {
      reviews: 'reviews',
      addToCart: 'Add to Cart',
      productId: 'Product ID',
      viewProduct: 'View Product',
      frequentlyBoughtTogether: 'Frequently Bought Together',
    }
  },
  id: {
    name: 'Bahasa Indonesia',
    code: 'id',
    common: {
      home: 'Beranda',
      products: 'Produk',
      recommendations: 'Rekomendasi',
      chatbot: 'Chatbot',
      profile: 'Profil',
      about: 'Tentang Kami',
      menu: 'Menu',
      logout: 'Keluar',
      login: 'Masuk',
      english: 'Bahasa Indonesia',
      thankYouForOrder: 'Terima kasih atas pesanan Anda!',
      orderPlacedSuccessfully: 'Pesanan Anda telah berhasil ditempatkan.',
      continueShopping: 'Lanjutkan Belanja',
      cart: 'Keranjang Belanja Anda',
      yourCartIsEmpty: 'Keranjang Anda kosong.',
      orderSummary: 'Ringkasan Pesanan',
      subtotal: 'Subtotal',
      shipping: 'Pengiriman',
      taxEst: 'Pajak (Perk.)',
      proceedToCheckout: 'Lanjutkan ke Checkout',
      noProductsFound: 'Tidak ada produk yang cocok dengan kriteria Anda.',
      editProfileComingSoon: 'Ubah Profil (Segera Hadir)',
      productsTitle: 'Produk',
      fertilizersNutrition: 'Pupuk & Nutrisi',
      pesticides: 'Pestisida',
      farmingTools: 'Alat Pertanian',
      premiumSeeds: 'Benih Unggul',
      servicesTitle: 'Layanan',
      palmpilotConsultation: 'Konsultasi PalmPilot',
      aiRecommendations: 'Rekomendasi AI',
      farmingGuides: 'Panduan Pertanian',
      technicalSupport: 'Dukungan Teknis',
      contactTitle: 'Kontak',
      allRightsReserved: 'Hak cipta dilindungi.',
      backToProducts: 'Kembali ke Produk',
      register: 'Daftar',
    },
    home: {
      welcomeTitle: 'Selamat Datang di PetanNaik!',
      heroSubtitle: 'Platform E-commerce Terpercaya untuk Petani Kelapa Sawit',
      startShopping: 'Mulai Belanja',
      learnMore: 'Pelajari Lebih Lanjut',
      aiRecommendationsTitle: 'Rekomendasi AI Untuk Anda',
      aiRecommendationsSubtitle: 'Berdasarkan analisis kebutuhan perkebunan Anda, kami merekomendasikan produk-produk terbaik ini',
      recommended: 'Direkomendasikan',
      refreshRecommendations: 'Segarkan Rekomendasi',
      popularProductsTitle: 'Produk Populer',
      whyChoosePetanNaik: 'Mengapa Memilih PetanNaik?',
      aiRecommendation: 'Rekomendasi AI',
      aiRecommendationBody: 'Dapatkan saran produk yang dipersonalisasi berdasarkan data pertanian dan kondisi lokal Anda.',
      qualityProducts: 'Produk Berkualitas',
      qualityProductsBody: 'Kami hanya menyediakan produk pertanian bersertifikat dan berkualitas tinggi untuk memastikan kesuksesan Anda.',
      palmpilotAssistant: 'Asisten PalmPilot',
      palmpilotAssistantBody: 'Chatbot AI kami siap 24/7 untuk menjawab pertanyaan pertanian Anda dan memberikan panduan ahli.',
    },
    chatbot: {
      title: 'PalmPilot Chatbot',
      placeholder: 'Ketik pesan Anda...',
      send: 'Kirim',
      clear: 'Hapus Chat',
      thinking: 'Sedang berpikir',
      error: 'Maaf, saya tidak mengerti.',
      connectionError: 'Maaf, terjadi kesalahan saat menghubungi chatbot API.',
      modelInfo: 'Chatbot ini menggunakan model Llama 2-7B',
      consultantTitle: 'Asisten PalmPilot',
      consultantSubtitle: 'Konsultan Pertanian AI Anda',
    },
    recommendations: {
      personalizedRecommendations: 'Dapatkan Rekomendasi Pribadi!',
      loginToReceiveSuggestions: 'Masuk untuk menerima saran yang disesuaikan dengan kebutuhan pertanian dan riwayat pembelian Anda.',
      loginOrSignUp: 'Masuk / Daftar',
      youMightAlsoLike: 'Anda Mungkin Juga Suka',
      generalFarmingInsights: 'Wawasan Pertanian Umum',
      exploreGuides: 'Jelajahi panduan kami untuk praktik terbaik dalam budidaya kelapa sawit, dari pemupukan hingga panen.',
      boostYieldWithNPKGold: 'Tingkatkan Hasil dengan NPK Gold',
      combatLeafSpotEffectively: 'Lawan Bintik Daun Secara Efektif',
      optimalHarvestingGuide: 'Panduan Panen Optimal',
      learnMore: 'Pelajari Lebih Lanjut',
      needSpecificAdvice: 'Butuh saran yang lebih spesifik?',
      askPalmpilot: 'Tanya PalmPilot',
    },
    products: {
      pageTitle: 'Produk Kami',
      searchPlaceholder: 'Cari produk...',
      priceRange: 'Rentang Harga',
      allPrices: 'Semua Harga',
      under: 'Di bawah',
      above: 'Di atas',
      category: 'Kategori',
      allCategories: 'Semua Kategori',
      applyFilters: 'Terapkan Filter',
      addToCart: 'Tambah ke Keranjang',
    },
    profile: {
      pageTitle: 'Profil Pengguna',
      fullName: 'Nama Lengkap',
      emailAddress: 'Alamat Email',
    },
    productDetail: {
      reviews: 'ulasan',
      addToCart: 'Tambah ke Keranjang',
      productId: 'ID Produk',
      viewProduct: 'Lihat Produk',
      frequentlyBoughtTogether: 'Sering Dibeli Bersama',
    }
  },
  jw: {
    name: 'Basa Jawa',
    code: 'jw',
    common: {
      home: 'Ndalem',
      products: 'Produk',
      recommendations: 'Rekomendasi',
      chatbot: 'Chatbot',
      profile: 'Profil',
      about: 'Babagan',
      menu: 'Menu',
      logout: 'Metu',
      login: 'Mlebu',
      english: 'Basa Jawa',
      thankYouForOrder: 'Matur nuwun pesenanipun!',
      orderPlacedSuccessfully: 'Pesenan sampeyan sampun kasil.',
      continueShopping: 'Lanjut Blanja',
      cart: 'Keranjang Blanja Sampeyan',
      yourCartIsEmpty: 'Keranjang sampeyan kosong.',
      orderSummary: 'Ringkesan Pesenan',
      subtotal: 'Subtotal',
      shipping: 'Pangiriman',
      taxEst: 'Pajak (Kinten-kinten)',
      proceedToCheckout: 'Lanjut menyang Checkout',
      noProductsFound: 'Mboten wonten produk ingkang cocog.',
      editProfileComingSoon: 'Owahi Profil (Badhe Rawuh)',
      productsTitle: 'Produk',
      fertilizersNutrition: 'Pupuk & Nutrisi',
      pesticides: 'Pestisida',
      farmingTools: 'Piranti Tani',
      premiumSeeds: 'Winih Unggul',
      servicesTitle: 'Layanan',
      palmpilotConsultation: 'Konsultasi PalmPilot',
      aiRecommendations: 'Rekomendasi AI',
      farmingGuides: 'Panduan Tani',
      technicalSupport: 'Dhukungan Teknis',
      contactTitle: 'Kontak',
      allRightsReserved: 'Kabeh hak dilindhungi.',
      backToProducts: 'Wangsul menyang Produk',
      register: 'Daftar',
    },
    home: {
      welcomeTitle: 'Sugeng Rawuh ing PetanNaik!',
      heroSubtitle: 'Platform E-commerce Paling Apik kanggo Petani Kelapa Sawit',
      startShopping: 'Miwiti Blanja',
      learnMore: 'Sinau Luwih Lanjut',
      aiRecommendationsTitle: 'Rekomendasi AI Kanggo Sampeyan',
      aiRecommendationsSubtitle: 'Adhedhasar analisis kabutuhan kebon sampeyan, kita nyaranake produk-produk paling apik iki',
      recommended: 'Disaranake',
      refreshRecommendations: 'Segerake Rekomendasi',
      popularProductsTitle: 'Produk Populer',
      whyChoosePetanNaik: 'Kenging Napa Milih PetanNaik?',
      aiRecommendation: 'Rekomendasi AI',
      aiRecommendationBody: 'Entuk saran produk pribadi adhedhasar data pertanian lan kahanan lokal sampeyan.',
      qualityProducts: 'Produk Kualitas',
      qualityProductsBody: 'Kita mung nyedhiyakake produk pertanian sing disertifikasi lan berkualitas tinggi kanggo njamin sukses sampeyan.',
      palmpilotAssistant: 'Asisten PalmPilot',
      palmpilotAssistantBody: 'Chatbot AI kita siyap 24/7 kanggo njawab pitakonan pertanian lan menehi pandhuan ahli.',
    },
    chatbot: {
      title: 'PalmPilot Chatbot',
      placeholder: 'Ketik pesen sampeyan...',
      send: 'Kirim',
      clear: 'Busak Chat',
      thinking: 'Mikir',
      error: 'Nyuwun pangapunten, kula mboten mangertos.',
      connectionError: 'Nyuwun pangapunten, wonten kesalahan nalika nyambung kaliyan chatbot API.',
      modelInfo: 'Chatbot niki ngangge model Llama 2-7B',
      consultantTitle: 'Asisten PalmPilot',
      consultantSubtitle: 'Konsultan Tani AI Sampeyan',
    },
    recommendations: {
      personalizedRecommendations: 'Entuk Rekomendasi Pribadi!',
      loginToReceiveSuggestions: 'Mlebu kanggo nampa saran sing dicocogake karo kabutuhan pertanian lan riwayat tuku sampeyan.',
      loginOrSignUp: 'Mlebu / Daftar',
      youMightAlsoLike: 'Sampeyan Mungkin Uga Seneng',
      generalFarmingInsights: 'Wawasan Tani Umum',
      exploreGuides: 'Jelajahi pandhuan kita kanggo praktik paling apik ing budidaya kelapa sawit, saka pemupukan nganti panen.',
      boostYieldWithNPKGold: 'Tambah Hasil karo NPK Gold',
      combatLeafSpotEffectively: 'Lawan Bintik Godhong Kanthi Efektif',
      optimalHarvestingGuide: 'Panduan Panen Optimal',
      learnMore: 'Sinau Luwih Lanjut',
      needSpecificAdvice: 'Butuh saran sing luwih spesifik?',
      askPalmpilot: 'Takon PalmPilot',
    },
    products: {
      pageTitle: 'Produk Kita',
      searchPlaceholder: 'Goleki produk...',
      priceRange: 'Rentang Rega',
      allPrices: 'Kabeh Rega',
      under: 'Ing sangisore',
      above: 'Ing dhuwure',
      category: 'Kategori',
      allCategories: 'Kabeh Kategori',
      applyFilters: 'Terapake Filter',
      addToCart: 'Tambah menyang Keranjang',
    },
    profile: {
      pageTitle: 'Profil Panganggo',
      fullName: 'Jeneng Jangkep',
      emailAddress: 'Alamat Email',
    },
    productDetail: {
      reviews: 'ulasan',
      addToCart: 'Tambah menyang Keranjang',
      productId: 'ID Produk',
      viewProduct: 'Deleng Produk',
      frequentlyBoughtTogether: 'Asring Dituku Bareng',
    }
  },
  su: {
    name: 'Basa Sunda',
    code: 'su',
    common: {
      home: 'Tepas',
      products: 'Produk',
      recommendations: 'Rekomendasi',
      chatbot: 'Chatbot',
      profile: 'Profil',
      about: 'Ngeunaan',
      menu: 'Menu',
      logout: 'Kaluar',
      login: 'Asup',
      english: 'Basa Sunda',
      thankYouForOrder: 'Hatur nuhun kana pesenan anjeun!',
      orderPlacedSuccessfully: 'Pesenan anjeun parantos suksés ditempatkeun.',
      continueShopping: 'Teraskeun Balanja',
      cart: 'Gorobag Balanja Anjeun',
      yourCartIsEmpty: 'Gorobag anjeun kosong.',
      orderSummary: 'Ringkesan Pesenan',
      subtotal: 'Subtotal',
      shipping: 'Pangiriman',
      taxEst: 'Pajeg (Kira-kira)',
      proceedToCheckout: 'Lajengkeun ka Checkout',
      noProductsFound: 'Teu aya produk anu cocog sareng kritéria anjeun.',
      editProfileComingSoon: 'Édit Profil (Moal lami deui)',
      productsTitle: 'Produk',
      fertilizersNutrition: 'Pupuk & Gizi',
      pesticides: 'Péstisida',
      farmingTools: 'Parabot Tani',
      premiumSeeds: 'Binih Unggul',
      servicesTitle: 'Layanan',
      palmpilotConsultation: 'Konsultasi PalmPilot',
      aiRecommendations: 'Rekomendasi AI',
      farmingGuides: 'Pituduh Tani',
      technicalSupport: 'Pangrojong Téknis',
      contactTitle: 'Kontak',
      allRightsReserved: 'Sadaya hak ditangtayungan.',
      backToProducts: 'Balik deui ka Produk',
      register: 'Daptar',
    },
    home: {
      welcomeTitle: 'Wilujeng Sumping di PetanNaik!',
      heroSubtitle: 'Platform E-commerce Anu Dipercaya pikeun Patani Kalapa Sawit',
      startShopping: 'Mimitian Balanja',
      learnMore: 'Diajar Langkung Seueur',
      aiRecommendationsTitle: 'Rekomendasi AI Pikeun Anjeun',
      aiRecommendationsSubtitle: 'Dumasar kana analisis kabutuhan kebon anjeun, kami nyarankeun produk-produk pangsaéna ieu',
      recommended: 'Disarankeun',
      refreshRecommendations: 'Segerkeun Rekomendasi',
      popularProductsTitle: 'Produk Populér',
      whyChoosePetanNaik: 'Naha Milih PetanNaik?',
      aiRecommendation: 'Rekomendasi AI',
      aiRecommendationBody: 'Kéngingkeun saran produk pribadi dumasar kana data tegalan anjeun sareng kaayaan lokal.',
      qualityProducts: 'Produk Kualitas',
      qualityProductsBody: 'Kami ngan ukur nyayogikeun produk tatanén anu disertipikasi sareng kualitas luhur pikeun mastikeun kasuksésan anjeun.',
      palmpilotAssistant: 'Asistén PalmPilot',
      palmpilotAssistantBody: 'Chatbot AI kami siap 24/7 pikeun ngajawab patarosan tatanén anjeun sareng masihan pituduh ahli.',
    },
    chatbot: {
      title: 'PalmPilot Chatbot',
      placeholder: 'Ketik pesen anjeun...',
      send: 'Kirim',
      clear: 'Hapus Chat',
      thinking: 'Mikir',
      error: 'Punten, abdi teu ngartos.',
      connectionError: 'Punten, aya kasalahan dina nyambungkeun ka chatbot API.',
      modelInfo: 'Chatbot ieu ngagunakeun model Llama 2-7B',
      consultantTitle: 'Asistén PalmPilot',
      consultantSubtitle: 'Konsultan Tatanén AI Anjeun',
    },
    recommendations: {
      personalizedRecommendations: 'Kéngingkeun Rekomendasi Pribadi!',
      loginToReceiveSuggestions: 'Asup pikeun nampi saran anu cocog sareng kabutuhan tegalan anjeun sareng riwayat pameseran.',
      loginOrSignUp: 'Asup / Daptar',
      youMightAlsoLike: 'Anjeun Mungkin Ogé Resep',
      generalFarmingInsights: 'Wawasan Tatanén Umum',
      exploreGuides: 'Jelajah pituduh kami pikeun prakték pangsaéna dina budidaya kalapa sawit, ti pemupukan dugi ka panén.',
      boostYieldWithNPKGold: 'Ningkatkeun Hasil ku NPK Gold',
      combatLeafSpotEffectively: 'Lawan Bintik Daun Sacara Éféktif',
      optimalHarvestingGuide: 'Pituduh Panén Optimal',
      learnMore: 'Diajar Langkung Seueur',
      needSpecificAdvice: 'Peryogi naséhat anu langkung spésifik?',
      askPalmpilot: 'Tanya PalmPilot',
    },
    products: {
      pageTitle: 'Produk Kami',
      searchPlaceholder: 'Milarian produk...',
      priceRange: 'Rentang Harga',
      allPrices: 'Sadaya Harga',
      under: 'Di handap',
      above: 'Di luhur',
      category: 'Kategori',
      allCategories: 'Sadaya Kategori',
      applyFilters: 'Larapkeun Filter',
      addToCart: 'Tambahkeun kana Gorobag',
    },
    profile: {
      pageTitle: 'Profil Pamaké',
      fullName: 'Nami Lengkep',
      emailAddress: 'Alamat Surélék',
    },
    productDetail: {
      reviews: 'ulasan',
      addToCart: 'Tambahkeun kana Gorobag',
      productId: 'ID Produk',
      viewProduct: 'Tingali Produk',
      frequentlyBoughtTogether: 'Sering Dibeuli Babarengan',
    }
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('id'); // Default to Indonesian

  const getMenuItems = () => [
    { text: languages[language].common.home, link: '/' },
    { text: languages[language].common.products, link: '/products' },
    { text: languages[language].common.recommendations, link: '/recommendations' },
    { text: languages[language].common.chatbot, link: '/chatbot' },
    { text: languages[language].common.profile, link: '/profile' },
    { text: languages[language].common.about, link: '/about' },
  ];

  const value = {
    language,
    setLanguage,
    translations: languages[language],
    getMenuItems,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);